services:
  - type: web
    name: cloud-ai
    env: node
    plan: free
    buildCommand: 'yarn install'
    startCommand: 'yarn start'
    envVars:
      - key: NODE_ENV
        value: production
    autoDeploy: true
